services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.lagoon
    labels:
      lagoon.type: node
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://node.docker.amazee.io
      - DEBUG=*
    networks:
      - amazeeio-network
      - default

  db:
    image: uselagoon/postgres-14:latest
    labels:
      lagoon.type: postgres

  cache:
    image: uselagoon/redis-6:latest
    labels:
      lagoon.type: redis


networks:
  amazeeio-network:
    external: true